export const assets = {
  letters: {
    a: require('@/assets/sign-language/letters/a.png'),
    b: require('@/assets/sign-language/letters/b.png'),
    c: require('@/assets/sign-language/letters/c.png'),
    d: require('@/assets/sign-language/letters/d.png'),
    e: require('@/assets/sign-language/letters/e.png'),
    f: require('@/assets/sign-language/letters/f.png'),
    g: require('@/assets/sign-language/letters/g.png'),
    h: require('@/assets/sign-language/letters/h.png'),
    i: require('@/assets/sign-language/letters/i.png'),
    j: require('@/assets/sign-language/letters/j.png'),
    k: require('@/assets/sign-language/letters/k.png'),
    l: require('@/assets/sign-language/letters/l.png'),
    m: require('@/assets/sign-language/letters/m.png'),
    n: require('@/assets/sign-language/letters/n.png'),
    o: require('@/assets/sign-language/letters/o.png'),
    p: require('@/assets/sign-language/letters/p.png'),
    q: require('@/assets/sign-language/letters/q.png'),
    r: require('@/assets/sign-language/letters/r.png'),
    s: require('@/assets/sign-language/letters/s.png'),
    t: require('@/assets/sign-language/letters/t.png'),
    u: require('@/assets/sign-language/letters/u.png'),
    v: require('@/assets/sign-language/letters/v.png'),
    w: require('@/assets/sign-language/letters/w.png'),
    x: require('@/assets/sign-language/letters/x.png'),
    y: require('@/assets/sign-language/letters/y.png'),
    z: require('@/assets/sign-language/letters/z.png'),
  },
  family: {
    aunt: require('@/assets/sign-language/family/AUNT.png'),
    baby: require('@/assets/sign-language/family/BABY.png'),
    brother: require('@/assets/sign-language/family/BROTHER.png'),
    father: require('@/assets/sign-language/family/FATHER.png'),
    mother: require('@/assets/sign-language/family/MOTHER.png'),
    grandfather: require('@/assets/sign-language/family/GRANDFATHER.png'),
    grandmother: require('@/assets/sign-language/family/GRANDMOTHER.png'),
  },
  colors: {
    black: require('@/assets/sign-language/colors/BLACK.png'),
    blue: require('@/assets/sign-language/colors/BLUE.png'),
    green: require('@/assets/sign-language/colors/GREEN.png'),
    orange: require('@/assets/sign-language/colors/ORANGE.png'),
    red: require('@/assets/sign-language/colors/RED.png'),
    white: require('@/assets/sign-language/colors/WHITE.png'),
    yellow: require('@/assets/sign-language/colors/YELLOW.png'),
  },
  basicWords: {
    above: require('@/assets/sign-language/basic-words/ABOVE.png'),
    add: require('@/assets/sign-language/basic-words/ADD.png'),
    adult: require('@/assets/sign-language/basic-words/ADULT.png'),
    again: require('@/assets/sign-language/basic-words/AGAIN.png'),
    airplane: require('@/assets/sign-language/basic-words/AIRPLANE.png'),
    all: require('@/assets/sign-language/basic-words/ALL.png'),
    allow: require('@/assets/sign-language/basic-words/ALLOW.png'),
    almost: require('@/assets/sign-language/basic-words/ALMOST.png'),
    around: require('@/assets/sign-language/basic-words/AROUND.png'),
    ask: require('@/assets/sign-language/basic-words/ASK.png'),
    back: require('@/assets/sign-language/basic-words/BACK.png'),
    bad: require('@/assets/sign-language/basic-words/BAD.png'),
    bag: require('@/assets/sign-language/basic-words/BAG.png'),
    bed: require('@/assets/sign-language/basic-words/BED.png'),
    eat: require('@/assets/sign-language/basic-words/EAT.png'),
    happy: require('@/assets/sign-language/basic-words/HAPPY.png'),
    help: require('@/assets/sign-language/basic-words/HELP.png'),
    hungry: require('@/assets/sign-language/basic-words/HUNGRY.png'),
    more: require('@/assets/sign-language/basic-words/MORE.png'),
    no: require('@/assets/sign-language/basic-words/NO.png'),
    please: require('@/assets/sign-language/basic-words/PLEASE.png'),
    scared: require('@/assets/sign-language/basic-words/SCARED.png'),
    sleep: require('@/assets/sign-language/basic-words/SLEEP.png'),
    want: require('@/assets/sign-language/basic-words/WANT.png'),
    water: require('@/assets/sign-language/basic-words/WATER.png'),
    yes: require('@/assets/sign-language/basic-words/YES.png'),
  },
  basicPhrase: {
    allDone: require('@/assets/sign-language/basic-phrase/ALL DONE.png'),
    beCareful: require('@/assets/sign-language/basic-phrase/BE CAREFUL.png'),
    birthday: require('@/assets/sign-language/basic-phrase/BIRTHDAY.png'),
    ILoveYou: require('@/assets/sign-language/basic-phrase/ILOVEYOU.png'),
    ThankYou: require('@/assets/sign-language/basic-phrase/THANKYOU.png'),
    YoureWelcome: require('@/assets/sign-language/basic-phrase/YOURE WELCOME.png'),
  },
  basicGreetings: {
    goodMorning: require('@/assets/sign-language/basic-greetings/GOOD MORNING.png'),
    goodNight: require('@/assets/sign-language/basic-greetings/GOODNIGHT.png'),
    hello: require('@/assets/sign-language/basic-greetings/HELLO.png'),
    welcome: require('@/assets/sign-language/basic-greetings/WELCOME.png'),
  },
  animals: {
    animal: require('@/assets/sign-language/animals/ANIMAL.png'),
    ant: require('@/assets/sign-language/animals/ANT.png'),
    bird: require('@/assets/sign-language/animals/BIRD.png'),
    cat: require('@/assets/sign-language/animals/CAT.png'),
    cow: require('@/assets/sign-language/animals/COW.png'),
    dog: require('@/assets/sign-language/animals/DOG.png'),
  }
} as const;

export default assets;