import assets from './asset-manager';
import { Level } from './level-schema';

const defaultLevels = [
  {
    id: 1,
    questions: [
      {
        image: assets.letters.j,
        label: 'What letter is this?',
        hint: 'Draws a letter in the air using the pinky.',
        choices: ['J', 'K'],
        correct: 0,
      },
      {
        image: assets.letters.g,
        label: 'Which letter is shown?',
        hint: 'Looks like a pointing gesture.',
        choices: ['F', 'G'],
        correct: 1,
      },
      {
        image: assets.letters.b,
        label: 'What letter is this hand sign for?',
        hint: 'A flat hand with fingers together.',
        choices: ['P', 'B'],
        correct: 1,
      },
      {
        image: assets.letters.k,
        label: 'What letter is this?',
        hint: "Middle finger forward, index and thumb create a 'K'.",
        choices: ['K', 'V'],
        correct: 0,
      },
      {
        image: assets.letters.f,
        label: 'Which letter is shown?',
        hint: 'OK hand shape.',
        choices: ['F', 'G'],
        correct: 0,
      },
      {
        image: assets.letters.m,
        label: 'What letter is this?',
        hint: 'Thumb under three fingers.',
        choices: ['O', 'M'],
        correct: 1,
      },
      {
        image: assets.letters.i,
        label: 'What letter is this?',
        hint: 'Only pinky finger is up.',
        choices: ['I', 'K'],
        correct: 0,
      },
      {
        image: assets.letters.a,
        label: 'What letter is this?',
        hint: 'A closed fist with the thumb on the side.',
        choices: ['S', 'A'],
        correct: 1,
      },
      {
        image: assets.letters.c,
        label: 'Which letter is this?',
        hint: 'Hand forms the shape of a curve.',
        choices: ['O', 'C'],
        correct: 1,
      },
      {
        image: assets.letters.l,
        label: 'Which letter is shown?',
        hint: "Index and thumb make an 'L'.",
        choices: ['L', 'V'],
        correct: 0,
      },
      {
        image: assets.letters.d,
        label: 'What letter is this?',
        hint: 'One finger up, thumb and other fingers form circle.',
        choices: ['D', 'E'],
        correct: 0,
      },
      {
        image: assets.letters.e,
        label: 'Which letter is shown?',
        hint: 'All fingers bent over the thumb.',
        choices: ['E', 'F'],
        correct: 0,
      },
      {
        image: assets.letters.h,
        label: 'What letter is this?',
        hint: 'Two fingers point sideways.',
        choices: ['J', 'H'],
        correct: 1,
      },
    ],
  },
  {
    id: 2,
    questions: [
      {
        image: assets.letters.r,
        label: 'What letter is this?',
        hint: 'Fingers crossed like a promise.',
        choices: ['R', 'S'],
        correct: 0,
      },
      {
        image: assets.letters.u,
        label: 'Which letter is shown?',
        hint: 'Two fingers held together upright.',
        choices: ['U', 'V'],
        correct: 0,
      },
      {
        image: assets.letters.v,
        label: 'What letter is this?',
        hint: 'Peace sign shape.',
        choices: ['V', 'U'],
        correct: 0,
      },
      {
        image: assets.letters.x,
        label: 'What letter is this?',
        hint: 'Looks like a hook shape.',
        choices: ['X', 'Y'],
        correct: 0,
      },
      {
        image: assets.letters.o,
        label: 'What letter is this?',
        hint: 'Fingers form a circle.',
        choices: ['O', 'C'],
        correct: 0,
      },
      {
        image: assets.letters.n,
        label: 'What letter is this?',
        hint: 'Thumb under two fingers.',
        choices: ['N', 'M'],
        correct: 0,
      },
      {
        image: assets.letters.q,
        label: 'What letter is shown?',
        hint: 'Hand points down with thumb and finger extended.',
        choices: ['Q', 'P'],
        correct: 0,
      },
      {
        image: assets.letters.p,
        label: 'What letter is this?',
        hint: 'Like a K but downward.',
        choices: ['P', 'Q'],
        correct: 0,
      },
      {
        image: assets.letters.s,
        label: 'Which letter is this?',
        hint: 'A fist with thumb across.',
        choices: ['S', 'A'],
        correct: 0,
      },
      {
        image: assets.letters.y,
        label: 'What letter is this?',
        hint: 'Thumb and pinky out.',
        choices: ['Y', 'X'],
        correct: 0,
      },
      {
        image: assets.letters.t,
        label: 'Which letter is this?',
        hint: 'Thumb between index and middle.',
        choices: ['T', 'F'],
        correct: 0,
      },
      {
        image: assets.letters.w,
        label: 'What letter is this?',
        hint: 'Three fingers up like a W.',
        choices: ['W', 'M'],
        correct: 0,
      },
      {
        image: assets.letters.z,
        label: 'What letter is shown?',
        hint: 'Draws a Z in the air.',
        choices: ['Z', 'N'],
        correct: 0,
      },
    ],
  },
  {
    id: 3,
    questions: [
      {
        image: assets.basicWords.please,
        label: 'What word is this?',
        hint: 'Used when requesting nicely.',
        choices: ['Please', 'Thank you'],
        correct: 0,
      },
      {
        image: assets.basicWords.eat,
        label: 'What does this sign mean?',
        hint: 'Relates to food.',
        choices: ['Eat', 'Drink'],
        correct: 0,
      },
      {
        image: assets.basicWords.hungry,
        label: 'What word is this?',
        hint: 'Your stomach feels empty.',
        choices: ['Hungry', 'Thirsty'],
        correct: 0,
      },
      {
        image: assets.basicWords.help,
        label: 'What word is this?',
        hint: 'You might shout it in an emergency.',
        choices: ['Help', 'No'],
        correct: 0,
      },
      {
        image: assets.basicWords.no,
        label: 'What is the word shown?',
        hint: 'Negative response.',
        choices: ['No', 'Yes'],
        correct: 0,
      },
      {
        image: assets.basicWords.yes,
        label: 'What does this sign mean?',
        hint: 'Positive response.',
        choices: ['Yes', 'No'],
        correct: 0,
      },
      {
        image: assets.basicWords.sleep,
        label: 'What does this sign indicate?',
        hint: 'Done at night in bed.',
        choices: ['Sleep', 'Eat'],
        correct: 0,
      },
      {
        image: assets.basicWords.again,
        label: 'What word is represented?',
        hint: 'You want a repeat.',
        choices: ['Again', 'More'],
        correct: 0,
      },
      {
        image: assets.basicGreetings.hello,
        label: 'Which greeting is this?',
        hint: 'Used when meeting someone.',
        choices: ['Hello', 'Goodbye'],
        correct: 0,
      },
      {
        image: assets.basicGreetings.goodMorning,
        label: 'What greeting is this?',
        hint: 'Said early in the day.',
        choices: ['Good Morning', 'Goodnight'],
        correct: 0,
      },
    ],
  },
  {
    id: 4,
    questions: [
      {
        image: assets.colors.red,
        label: 'What color is this?',
        hint: 'Color of apples.',
        choices: ['Red', 'Green'],
        correct: 0,
      },
      {
        image: assets.colors.yellow,
        label: 'What color is this?',
        hint: 'Color of bananas.',
        choices: ['Yellow', 'Blue'],
        correct: 0,
      },
      {
        image: assets.colors.orange,
        label: 'What color is this?',
        hint: 'Also a fruit.',
        choices: ['Orange', 'Red'],
        correct: 0,
      },
      {
        image: assets.colors.blue,
        label: 'What color is shown?',
        hint: 'Color of the sky.',
        choices: ['Blue', 'Green'],
        correct: 0,
      },
      {
        image: assets.colors.green,
        label: 'What color is this?',
        hint: 'Color of grass.',
        choices: ['Green', 'Black'],
        correct: 0,
      },
      {
        image: assets.colors.black,
        label: 'What color is this?',
        hint: 'Opposite of white.',
        choices: ['Black', 'Red'],
        correct: 0,
      },
      {
        image: assets.colors.white,
        label: 'What color is shown?',
        hint: 'Color of snow.',
        choices: ['White', 'Blue'],
        correct: 0,
      },
    ],
  },
  {
    id: 5,
    questions: [
      {
        image: assets.family.mother,
        label: 'Who is this?',
        hint: 'Female parent.',
        choices: ['Mother', 'Aunt'],
        correct: 0,
      },
      {
        image: assets.family.father,
        label: 'Who is this?',
        hint: 'Male parent.',
        choices: ['Father', 'Grandfather'],
        correct: 0,
      },
      {
        image: assets.family.brother,
        label: 'What family member is this?',
        hint: 'Male sibling.',
        choices: ['Brother', 'Uncle'],
        correct: 0,
      },
      {
        image: assets.family.grandmother,
        label: 'Who is this?',
        hint: "Mother's mother.",
        choices: ['Grandmother', 'Aunt'],
        correct: 0,
      },
      {
        image: assets.animals.cat,
        label: 'What animal is this?',
        hint: "Says 'meow'.",
        choices: ['Cat', 'Dog'],
        correct: 0,
      },
      {
        image: assets.animals.dog,
        label: 'What animal is shown?',
        hint: 'Barks.',
        choices: ['Dog', 'Cat'],
        correct: 0,
      },
      {
        image: assets.animals.bird,
        label: 'Which animal does this sign represent?',
        hint: 'It can fly.',
        choices: ['Bird', 'Cow'],
        correct: 0,
      },
      {
        image: assets.animals.cow,
        label: 'What animal is this?',
        hint: 'Gives milk.',
        choices: ['Cow', 'Bird'],
        correct: 0,
      },
      {
        image: assets.basicPhrase.ThankYou,
        label: 'What phrase is this?',
        hint: 'Used to express gratitude.',
        choices: ['Thank you', "You're welcome"],
        correct: 0,
      },
      {
        image: assets.basicPhrase.YoureWelcome,
        label: 'What phrase is this?',
        hint: "Said after 'thank you'.",
        choices: ["You're welcome", 'Goodbye'],
        correct: 0,
      },
    ],
  },
].map<Level>((l) => ({
  ...l,
  questions: l.questions.map((q) => ({ ...q, completed: false })),
  completed: false,
}));

export default defaultLevels;
